// Code generated by promise-go. DO NOT EDIT.

package task

import "errors"

var ErrInvalidTaskStatusTransition = errors.New("Task: status transition")

func CanTransitionTaskStatus(from TaskStatus, to TaskStatus) bool {
	switch from {
	case TaskStatusTodo:
		switch to {
		case TaskStatusDone:
			return true
		}
		return false
	case TaskStatusDone:
		switch to {
		case TaskStatusTodo:
			return true
		}
		return false
	default:
		return false
	}
}

func ValidateTaskStatusTransition(from TaskStatus, to TaskStatus) error {
	if CanTransitionTaskStatus(from, to) {
		return nil
	}
	return ErrInvalidTaskStatusTransition
}
