// Code generated by promise-go. DO NOT EDIT.

package task

import "errors"

var ErrTaskInvariantViolation = errors.New("Task: invariant violation")

func ValidateTaskPromise(value Task) error {
	switch value.Status {
	case TaskStatusTodo, TaskStatusDone:
		// declared state
	default:
		return ErrTaskInvariantViolation
	}
	// Task.done_requires_completedAt: When Task.status is done, Task.completedAt must exist.
	if value.Status == TaskStatusDone && value.CompletedAt == nil {
		return ErrTaskInvariantViolation
	}
	// Task.todo_requires_null_completedAt: When Task.status is todo, Task.completedAt must be null.
	if value.Status == TaskStatusTodo && value.CompletedAt != nil {
		return ErrTaskInvariantViolation
	}
	// Task.createdAt_immutable: Task.createdAt cannot be changed by business actions.
	// Not yet enforced by the Go target; keep this Promise claim covered by tests or handwritten guards.
	return nil
}
