// Code generated by promise-go. DO NOT EDIT.

package task

import "time"

type TaskID string

type TaskStatus string

const (
	TaskStatusTodo TaskStatus = "todo"
	TaskStatusDone TaskStatus = "done"
)

type Task struct {
	ID TaskID `json:"id"`
	Title string `json:"title"`
	Status TaskStatus `json:"status"`
	CompletedAt *time.Time `json:"completedAt,omitempty"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}
